// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Category$CoreCategory = require("./Category.bs.js");

function Make2(X) {
  var include = Category$CoreCategory.Make2(X);
  var product = X.product;
  var CartesianInfix = {
    $pipe$star$pipe: product
  };
  return {
          id: X.id,
          compose: X.compose,
          CategoryInfix: include.CategoryInfix,
          $less$less: include.$less$less,
          $great$great: include.$great$great,
          product: product,
          exl: X.exl,
          exr: X.exr,
          CartesianInfix: CartesianInfix,
          $pipe$star$pipe: product
        };
}

exports.Make2 = Make2;
/* No side effect */
