// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Cartesian$CoreCategory = require("./Cartesian.bs.js");

function Make2(X) {
  var include = Cartesian$CoreCategory.Make2(X);
  return {
          ap: X.ap,
          curry: X.curry,
          uncurry: X.uncurry,
          id: X.id,
          compose: X.compose,
          CategoryInfix: include.CategoryInfix,
          $less$less: include.$less$less,
          $great$great: include.$great$great,
          product: X.product,
          exl: X.exl,
          exr: X.exr,
          CartesianInfix: include.CartesianInfix,
          $pipe$star$pipe: include.$pipe$star$pipe
        };
}

exports.Make2 = Make2;
/* No side effect */
