// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Category$CoreCategory = require("./Category.bs.js");

function Make2(X) {
  var include = Category$CoreCategory.Make2(X);
  var sum = X.sum;
  var CocartesianInfix = {
    $pipe$plus$pipe: sum
  };
  return {
          id: X.id,
          compose: X.compose,
          CategoryInfix: include.CategoryInfix,
          $less$less: include.$less$less,
          $great$great: include.$great$great,
          inl: X.inl,
          inr: X.inr,
          sum: sum,
          CocartesianInfix: CocartesianInfix,
          $pipe$plus$pipe: sum
        };
}

exports.Make2 = Make2;
/* No side effect */
