// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Fun$CoreCategory = require("./Fun.bs.js");

function S_to_S2(X) {
  return {
          contramap: X.contramap,
          contramapConst: X.contramapConst,
          Contravariant_infix: X.Contravariant_infix,
          $great$$less: X.$great$$less,
          $great$: X.$great$,
          $great$$$less: X.$great$$$less,
          $$less: X.$$less
        };
}

function S2_to_S(X) {
  return {
          contramap: X.contramap,
          contramapConst: X.contramapConst,
          Contravariant_infix: X.Contravariant_infix,
          $great$$less: X.$great$$less,
          $great$: X.$great$,
          $great$$$less: X.$great$$$less,
          $$less: X.$$less
        };
}

function S2_to_S3(X) {
  return {
          contramap: X.contramap,
          contramapConst: X.contramapConst,
          Contravariant_infix: X.Contravariant_infix,
          $great$$less: X.$great$$less,
          $great$: X.$great$,
          $great$$$less: X.$great$$$less,
          $$less: X.$$less
        };
}

function S3_to_S2(X) {
  return {
          contramap: X.contramap,
          contramapConst: X.contramapConst,
          Contravariant_infix: X.Contravariant_infix,
          $great$$less: X.$great$$less,
          $great$: X.$great$,
          $great$$$less: X.$great$$$less,
          $$less: X.$$less
        };
}

function Make3(X) {
  var contramap = X.contramap;
  var match = X.contramapConst;
  var contramapConst = typeof match === "number" ? (function (x, c) {
        return Curry._2(contramap, x, (function (param) {
                      return Fun$CoreCategory.$$const(c, param);
                    }));
      }) : match[1];
  var $great$$less = function (f, x) {
    return Curry._2(contramap, x, f);
  };
  var $great$$$less = Curry.__2(contramap);
  var $great$ = function (x, t) {
    return Curry._2(contramapConst, t, x);
  };
  var $$less = Curry.__2(contramapConst);
  return {
          contramap: contramap,
          contramapConst: contramapConst,
          Contravariant_infix: {
            $great$$less: $great$$less,
            $great$: $great$,
            $great$$$less: $great$$$less,
            $$less: $$less
          },
          $great$$less: $great$$less,
          $great$: $great$,
          $great$$$less: $great$$$less,
          $$less: $$less
        };
}

function Make2(X) {
  var contramap = X.contramap;
  var contramapConst = X.contramapConst;
  var contramapConst$1 = typeof contramapConst === "number" ? (function (x, c) {
        return Curry._2(contramap, x, (function (param) {
                      return Fun$CoreCategory.$$const(c, param);
                    }));
      }) : contramapConst[1];
  var $great$$less = function (f, x) {
    return Curry._2(contramap, x, f);
  };
  var $great$$$less = Curry.__2(contramap);
  var $great$ = function (x, t) {
    return Curry._2(contramapConst$1, t, x);
  };
  var $$less = Curry.__2(contramapConst$1);
  return {
          contramap: contramap,
          contramapConst: contramapConst$1,
          Contravariant_infix: {
            $great$$less: $great$$less,
            $great$: $great$,
            $great$$$less: $great$$$less,
            $$less: $$less
          },
          $great$$less: $great$$less,
          $great$: $great$,
          $great$$$less: $great$$$less,
          $$less: $$less
        };
}

function Make(X) {
  var contramap = X.contramap;
  var contramapConst = X.contramapConst;
  var contramapConst$1 = typeof contramapConst === "number" ? (function (x, c) {
        return Curry._2(contramap, x, (function (param) {
                      return Fun$CoreCategory.$$const(c, param);
                    }));
      }) : contramapConst[1];
  var $great$$less = function (f, x) {
    return Curry._2(contramap, x, f);
  };
  var $great$$$less = Curry.__2(contramap);
  var $great$ = function (x, t) {
    return Curry._2(contramapConst$1, t, x);
  };
  var $$less = Curry.__2(contramapConst$1);
  return {
          contramap: contramap,
          contramapConst: contramapConst$1,
          Contravariant_infix: {
            $great$$less: $great$$less,
            $great$: $great$,
            $great$$$less: $great$$$less,
            $$less: $$less
          },
          $great$$less: $great$$less,
          $great$: $great$,
          $great$$$less: $great$$$less,
          $$less: $$less
        };
}

exports.S_to_S2 = S_to_S2;
exports.S2_to_S = S2_to_S;
exports.S2_to_S3 = S2_to_S3;
exports.S3_to_S2 = S3_to_S2;
exports.Make3 = Make3;
exports.Make2 = Make2;
exports.Make = Make;
/* Fun-CoreCategory Not a pure module */
