// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function S1_to_S2(X) {
  return X;
}

function S2_to_S1(X) {
  return X;
}

function S2_to_S3(X) {
  return X;
}

function S3_to_S2(X) {
  return X;
}

function MakeCustom3(X) {
  var cmap = X.cmap;
  var match = X.creplace;
  var creplace;
  var exit = 0;
  if (typeof match === "number" || match[0] !== -198771759) {
    exit = 1;
  } else {
    creplace = match[1];
  }
  if (exit === 1) {
    creplace = (function (x, $$const) {
        return Curry._2(cmap, x, (function (param) {
                      return $$const;
                    }));
      });
  }
  var $great$$less = function (f, x) {
    return Curry._2(cmap, x, f);
  };
  var $great$$$less = Curry.__2(cmap);
  var $great$ = function ($$const, t) {
    return Curry._2(creplace, t, $$const);
  };
  var $$less = Curry.__2(creplace);
  return {
          cmap: cmap,
          creplace: creplace,
          ContravariantInfix: {
            $great$$less: $great$$less,
            $great$: $great$,
            $great$$$less: $great$$$less,
            $$less: $$less
          },
          $great$$less: $great$$less,
          $great$: $great$,
          $great$$$less: $great$$$less,
          $$less: $$less
        };
}

function MakeCustom2(X) {
  var cmap = X.cmap;
  var creplace = X.creplace;
  var creplace$1;
  var exit = 0;
  if (typeof creplace === "number" || creplace[0] !== -198771759) {
    exit = 1;
  } else {
    creplace$1 = creplace[1];
  }
  if (exit === 1) {
    creplace$1 = (function (x, $$const) {
        return Curry._2(cmap, x, (function (param) {
                      return $$const;
                    }));
      });
  }
  var $great$$less = function (f, x) {
    return Curry._2(cmap, x, f);
  };
  var $great$$$less = Curry.__2(cmap);
  var $great$ = function ($$const, t) {
    return Curry._2(creplace$1, t, $$const);
  };
  var $$less = Curry.__2(creplace$1);
  return {
          cmap: cmap,
          creplace: creplace$1,
          ContravariantInfix: {
            $great$$less: $great$$less,
            $great$: $great$,
            $great$$$less: $great$$$less,
            $$less: $$less
          },
          $great$$less: $great$$less,
          $great$: $great$,
          $great$$$less: $great$$$less,
          $$less: $$less
        };
}

function MakeCustom1(X) {
  var cmap = X.cmap;
  var creplace = X.creplace;
  var creplace$1;
  var exit = 0;
  if (typeof creplace === "number" || creplace[0] !== -198771759) {
    exit = 1;
  } else {
    creplace$1 = creplace[1];
  }
  if (exit === 1) {
    creplace$1 = (function (x, $$const) {
        return Curry._2(cmap, x, (function (param) {
                      return $$const;
                    }));
      });
  }
  var $great$$less = function (f, x) {
    return Curry._2(cmap, x, f);
  };
  var $great$$$less = Curry.__2(cmap);
  var $great$ = function ($$const, t) {
    return Curry._2(creplace$1, t, $$const);
  };
  var $$less = Curry.__2(creplace$1);
  return {
          cmap: cmap,
          creplace: creplace$1,
          ContravariantInfix: {
            $great$$less: $great$$less,
            $great$: $great$,
            $great$$$less: $great$$$less,
            $$less: $$less
          },
          $great$$less: $great$$less,
          $great$: $great$,
          $great$$$less: $great$$$less,
          $$less: $$less
        };
}

function Make3(X) {
  var cmap = X.cmap;
  var creplace;
  var exit = 0;
  exit = 1;
  if (exit === 1) {
    creplace = (function (x, $$const) {
        return Curry._2(cmap, x, (function (param) {
                      return $$const;
                    }));
      });
  }
  var $great$$less = function (f, x) {
    return Curry._2(cmap, x, f);
  };
  var $great$$$less = Curry.__2(cmap);
  var $great$ = function ($$const, t) {
    return Curry._2(creplace, t, $$const);
  };
  var $$less = Curry.__2(creplace);
  return {
          cmap: cmap,
          creplace: creplace,
          ContravariantInfix: {
            $great$$less: $great$$less,
            $great$: $great$,
            $great$$$less: $great$$$less,
            $$less: $$less
          },
          $great$$less: $great$$less,
          $great$: $great$,
          $great$$$less: $great$$$less,
          $$less: $$less
        };
}

function Make2(X) {
  var cmap = X.cmap;
  var creplace;
  var exit = 0;
  exit = 1;
  if (exit === 1) {
    creplace = (function (x, $$const) {
        return Curry._2(cmap, x, (function (param) {
                      return $$const;
                    }));
      });
  }
  var $great$$less = function (f, x) {
    return Curry._2(cmap, x, f);
  };
  var $great$$$less = Curry.__2(cmap);
  var $great$ = function ($$const, t) {
    return Curry._2(creplace, t, $$const);
  };
  var $$less = Curry.__2(creplace);
  return {
          cmap: cmap,
          creplace: creplace,
          ContravariantInfix: {
            $great$$less: $great$$less,
            $great$: $great$,
            $great$$$less: $great$$$less,
            $$less: $$less
          },
          $great$$less: $great$$less,
          $great$: $great$,
          $great$$$less: $great$$$less,
          $$less: $$less
        };
}

function Make1(X) {
  var cmap = X.cmap;
  var creplace;
  var exit = 0;
  exit = 1;
  if (exit === 1) {
    creplace = (function (x, $$const) {
        return Curry._2(cmap, x, (function (param) {
                      return $$const;
                    }));
      });
  }
  var $great$$less = function (f, x) {
    return Curry._2(cmap, x, f);
  };
  var $great$$$less = Curry.__2(cmap);
  var $great$ = function ($$const, t) {
    return Curry._2(creplace, t, $$const);
  };
  var $$less = Curry.__2(creplace);
  return {
          cmap: cmap,
          creplace: creplace,
          ContravariantInfix: {
            $great$$less: $great$$less,
            $great$: $great$,
            $great$$$less: $great$$$less,
            $$less: $$less
          },
          $great$$less: $great$$less,
          $great$: $great$,
          $great$$$less: $great$$$less,
          $$less: $$less
        };
}

exports.S1_to_S2 = S1_to_S2;
exports.S2_to_S1 = S2_to_S1;
exports.S2_to_S3 = S2_to_S3;
exports.S3_to_S2 = S3_to_S2;
exports.MakeCustom3 = MakeCustom3;
exports.MakeCustom2 = MakeCustom2;
exports.MakeCustom1 = MakeCustom1;
exports.Make3 = Make3;
exports.Make2 = Make2;
exports.Make1 = Make1;
/* No side effect */
