// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Fun$CoreCategory = require("./Fun.bs.js");
var Monoid$CoreCategory = require("./Monoid.bs.js");

function Make0(M) {
  var abs = function (t) {
    return Curry._1(t, M.empty);
  };
  var rep = M.combine;
  var empty = Curry._1(rep, M.empty);
  var include = Monoid$CoreCategory.Make0({
        combine: Fun$CoreCategory.compose,
        empty: empty
      });
  return {
          empty: include.empty,
          combine: include.combine,
          Semigroup_infix: include.Semigroup_infix,
          $less$great: include.$less$great,
          abs: abs,
          rep: rep
        };
}

exports.Make0 = Make0;
/* Fun-CoreCategory Not a pure module */
