// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Fun$CoreCategory = require("./Fun.bs.js");

function first(a) {
  return /* First */Block.__(0, [a]);
}

function second(a) {
  return /* Second */Block.__(1, [a]);
}

function either(first, second, param) {
  if (param.tag) {
    return Curry._1(second, param[0]);
  } else {
    return Curry._1(first, param[0]);
  }
}

function bimap(x, f, g) {
  if (x.tag) {
    return /* Second */Block.__(1, [Curry._1(g, x[0])]);
  } else {
    return /* First */Block.__(0, [Curry._1(f, x[0])]);
  }
}

function map(x, f) {
  return bimap(x, f, Fun$CoreCategory.id);
}

exports.first = first;
exports.second = second;
exports.either = either;
exports.bimap = bimap;
exports.map = map;
/* Fun-CoreCategory Not a pure module */
