// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Monad$CoreCategory = require("./Monad.bs.js");
var Semigroup$CoreCategory = require("./Semigroup.bs.js");
var EitherBase$CoreCategory = require("./EitherBase.bs.js");

var map = /* `Custom */[
  -198771759,
  EitherBase$CoreCategory.mapFirst
];

var pure = EitherBase$CoreCategory.first;

function bind(x, f) {
  if (x.tag) {
    return /* Second */Block.__(1, [x[0]]);
  } else {
    return Curry._1(f, x[0]);
  }
}

function apply_(x, f) {
  if (f.tag) {
    return /* Second */Block.__(1, [f[0]]);
  } else {
    return Curry._2(EitherBase$CoreCategory.mapFirst, x, f[0]);
  }
}

var apply = /* `Custom */[
  -198771759,
  apply_
];

var include = Monad$CoreCategory.MakeCustom2({
      pure: pure,
      bind: bind,
      map: map,
      replace: /* Derived */-684824643,
      apply: apply,
      liftA2: /* Derived */-684824643,
      applyFirst: /* Derived */-684824643,
      applySecond: /* Derived */-684824643,
      select: /* Derived */-684824643,
      join: /* Derived */-684824643
    });

function append(a, b) {
  if (a.tag) {
    return b;
  } else {
    return a;
  }
}

var include$1 = Semigroup$CoreCategory.Make2({
      append: append
    });

var first = EitherBase$CoreCategory.first;

var second = EitherBase$CoreCategory.second;

var either = EitherBase$CoreCategory.either;

var isFirst = EitherBase$CoreCategory.isFirst;

var isSecond = EitherBase$CoreCategory.isSecond;

var fromFirst = EitherBase$CoreCategory.fromFirst;

var fromSecond = EitherBase$CoreCategory.fromSecond;

var bimap = EitherBase$CoreCategory.bimap;

var mapFirst = EitherBase$CoreCategory.mapFirst;

var mapSecond = EitherBase$CoreCategory.mapSecond;

var map$1 = include.map;

var replace = include.replace;

var $$void = include.$$void;

var FunctorInfix = include.FunctorInfix;

var $less$$great = include.$less$$great;

var $less$amp$great = include.$less$amp$great;

var $less$ = include.$less$;

var $$great = include.$$great;

var apply$1 = include.apply;

var applyFirst = include.applyFirst;

var applySecond = include.applySecond;

var liftA2 = include.liftA2;

var ApplyInfix = include.ApplyInfix;

var $less$star$great = include.$less$star$great;

var $star$great = include.$star$great;

var $less$star = include.$less$star;

var $star$star = include.$star$star;

var liftA3 = include.liftA3;

var liftA4 = include.liftA4;

var liftA5 = include.liftA5;

var merge = include.merge;

var pure$1 = include.pure;

var when_ = include.when_;

var unless = include.unless;

var select = include.select;

var SelectiveInfix = include.SelectiveInfix;

var $less$star$question = include.$less$star$question;

var $less$pipe$pipe$great = include.$less$pipe$pipe$great;

var $less$amp$amp$great = include.$less$amp$amp$great;

var orS = include.orS;

var andS = include.andS;

var whenS = include.whenS;

var branch = include.branch;

var ifS = include.ifS;

var fromOptionS = include.fromOptionS;

var anyS = include.anyS;

var allS = include.allS;

var whileS = include.whileS;

var bind$1 = include.bind;

var MonadInfix = include.MonadInfix;

var $great$great$eq = include.$great$great$eq;

var $great$great$tilde = include.$great$great$tilde;

var $great$eq$great = include.$great$eq$great;

var join = include.join;

var forever = include.forever;

var sequenceM = include.sequenceM;

var mapM = include.mapM;

var mapM_ = include.mapM_;

var append$1 = include$1.append;

var SemigroupInfix = include$1.SemigroupInfix;

var $less$great = include$1.$less$great;

exports.first = first;
exports.second = second;
exports.either = either;
exports.isFirst = isFirst;
exports.isSecond = isSecond;
exports.fromFirst = fromFirst;
exports.fromSecond = fromSecond;
exports.bimap = bimap;
exports.mapFirst = mapFirst;
exports.mapSecond = mapSecond;
exports.map = map$1;
exports.replace = replace;
exports.$$void = $$void;
exports.FunctorInfix = FunctorInfix;
exports.$less$$great = $less$$great;
exports.$less$amp$great = $less$amp$great;
exports.$less$ = $less$;
exports.$$great = $$great;
exports.apply = apply$1;
exports.applyFirst = applyFirst;
exports.applySecond = applySecond;
exports.liftA2 = liftA2;
exports.ApplyInfix = ApplyInfix;
exports.$less$star$great = $less$star$great;
exports.$star$great = $star$great;
exports.$less$star = $less$star;
exports.$star$star = $star$star;
exports.liftA3 = liftA3;
exports.liftA4 = liftA4;
exports.liftA5 = liftA5;
exports.merge = merge;
exports.pure = pure$1;
exports.when_ = when_;
exports.unless = unless;
exports.select = select;
exports.SelectiveInfix = SelectiveInfix;
exports.$less$star$question = $less$star$question;
exports.$less$pipe$pipe$great = $less$pipe$pipe$great;
exports.$less$amp$amp$great = $less$amp$amp$great;
exports.orS = orS;
exports.andS = andS;
exports.whenS = whenS;
exports.branch = branch;
exports.ifS = ifS;
exports.fromOptionS = fromOptionS;
exports.anyS = anyS;
exports.allS = allS;
exports.whileS = whileS;
exports.bind = bind$1;
exports.MonadInfix = MonadInfix;
exports.$great$great$eq = $great$great$eq;
exports.$great$great$tilde = $great$great$tilde;
exports.$great$eq$great = $great$eq$great;
exports.join = join;
exports.forever = forever;
exports.sequenceM = sequenceM;
exports.mapM = mapM;
exports.mapM_ = mapM_;
exports.append = append$1;
exports.SemigroupInfix = SemigroupInfix;
exports.$less$great = $less$great;
/* include Not a pure module */
