// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var List$CoreCategory = require("./List.bs.js");
var Semigroup$CoreCategory = require("./Semigroup.bs.js");

function head(param) {
  return param[0];
}

function tail(param) {
  var xs = param[1];
  if (xs) {
    return /* NonEmpty */[
            xs[0],
            xs[1]
          ];
  }
  
}

function cons(x, param) {
  return /* NonEmpty */[
          x,
          /* :: */[
            param[0],
            param[1]
          ]
        ];
}

function map(param, f) {
  return /* NonEmpty */[
          Curry._1(f, param[0]),
          Curry._2(List$CoreCategory.map, param[1], f)
        ];
}

function singleton(x) {
  return /* NonEmpty */[
          x,
          /* [] */0
        ];
}

function append(param, param$1) {
  return /* NonEmpty */[
          param[0],
          Pervasives.$at(param[1], /* :: */[
                param$1[0],
                param$1[1]
              ])
        ];
}

var include = Semigroup$CoreCategory.Make({
      combine: append
    });

var combine = include.combine;

var Semigroup_infix = include.Semigroup_infix;

var $less$great = include.$less$great;

exports.head = head;
exports.tail = tail;
exports.cons = cons;
exports.map = map;
exports.singleton = singleton;
exports.append = append;
exports.combine = combine;
exports.Semigroup_infix = Semigroup_infix;
exports.$less$great = $less$great;
/* include Not a pure module */
