// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Monad$CoreCategory = require("./Monad.bs.js");

function oneOf(xs) {
  return Promise.race(xs);
}

function fail(x) {
  return Promise.reject(x);
}

function $$catch(x, f) {
  return x.catch((function (y) {
                return Promise.resolve(Curry._1(f, y));
              }));
}

function $$return(x) {
  return Promise.resolve(x);
}

function bind(x, f) {
  return x.then(Curry.__1(f));
}

var include = Monad$CoreCategory.Make({
      $$return: $$return,
      bind: bind,
      apply: /* Using_bind */301992440,
      map: /* Using_apply */524559571,
      liftA2: /* Using_apply */524559571,
      liftA3: /* Using_apply */524559571,
      discardFirst: /* Using_apply */524559571,
      discardSecond: /* Using_apply */524559571,
      select: /* Using_bind */301992440
    });

function sequence(xs) {
  return Promise.all(xs);
}

function sequence2(x2) {
  return Promise.all(x2);
}

function sequence3(x3) {
  return Promise.all(x3);
}

function sequence4(x4) {
  return Promise.all(x4);
}

function sequence5(x5) {
  return Promise.all(x5);
}

function sequence6(x6) {
  return Promise.all(x6);
}

var select = include.select;

var $$void = include.$$void;

var Functor_infix = include.Functor_infix;

var $less$$great = include.$less$$great;

var $less$amp$great = include.$less$amp$great;

var $less$ = include.$less$;

var $$great = include.$$great;

var $$return$1 = include.$$return;

var apply = include.apply;

var liftA2 = include.liftA2;

var liftA3 = include.liftA3;

var discardFirst = include.discardFirst;

var discardSecond = include.discardSecond;

var map = include.map;

var unit = include.unit;

var merge = include.merge;

var Applicative_infix = include.Applicative_infix;

var $less$star$great = include.$less$star$great;

var $star$great = include.$star$great;

var $less$star = include.$less$star;

var $star$star = include.$star$star;

var Selective_infix = include.Selective_infix;

var $less$star$question = include.$less$star$question;

var $less$pipe$pipe$great = include.$less$pipe$pipe$great;

var $less$amp$amp$great = include.$less$amp$amp$great;

var orS = include.orS;

var andS = include.andS;

var whenS = include.whenS;

var branch = include.branch;

var ifS = include.ifS;

var fromOptionS = include.fromOptionS;

var anyS = include.anyS;

var allS = include.allS;

var whileS = include.whileS;

var bind$1 = include.bind;

var Monad_infix = include.Monad_infix;

var $great$great$eq = include.$great$great$eq;

var $great$great$tilde = include.$great$great$tilde;

var $great$eq$great = include.$great$eq$great;

var join = include.join;

var forever = include.forever;

var sequenceM = include.sequenceM;

var mapM = include.mapM;

var mapM_ = include.mapM_;

exports.oneOf = oneOf;
exports.fail = fail;
exports.$$catch = $$catch;
exports.select = select;
exports.$$void = $$void;
exports.Functor_infix = Functor_infix;
exports.$less$$great = $less$$great;
exports.$less$amp$great = $less$amp$great;
exports.$less$ = $less$;
exports.$$great = $$great;
exports.$$return = $$return$1;
exports.apply = apply;
exports.liftA2 = liftA2;
exports.liftA3 = liftA3;
exports.discardFirst = discardFirst;
exports.discardSecond = discardSecond;
exports.map = map;
exports.unit = unit;
exports.merge = merge;
exports.Applicative_infix = Applicative_infix;
exports.$less$star$great = $less$star$great;
exports.$star$great = $star$great;
exports.$less$star = $less$star;
exports.$star$star = $star$star;
exports.Selective_infix = Selective_infix;
exports.$less$star$question = $less$star$question;
exports.$less$pipe$pipe$great = $less$pipe$pipe$great;
exports.$less$amp$amp$great = $less$amp$amp$great;
exports.orS = orS;
exports.andS = andS;
exports.whenS = whenS;
exports.branch = branch;
exports.ifS = ifS;
exports.fromOptionS = fromOptionS;
exports.anyS = anyS;
exports.allS = allS;
exports.whileS = whileS;
exports.bind = bind$1;
exports.Monad_infix = Monad_infix;
exports.$great$great$eq = $great$great$eq;
exports.$great$great$tilde = $great$great$tilde;
exports.$great$eq$great = $great$eq$great;
exports.join = join;
exports.forever = forever;
exports.sequenceM = sequenceM;
exports.mapM = mapM;
exports.mapM_ = mapM_;
exports.sequence = sequence;
exports.sequence2 = sequence2;
exports.sequence3 = sequence3;
exports.sequence4 = sequence4;
exports.sequence5 = sequence5;
exports.sequence6 = sequence6;
/* include Not a pure module */
