// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Monad$CoreCategory = require("./Monad.bs.js");

function oneOf(xs) {
  return Promise.race(Belt_List.toArray(xs));
}

function fail(x) {
  return Promise.reject(x);
}

function $$catch(x, f) {
  return x.catch((function (y) {
                return Promise.resolve(Curry._1(f, y));
              }));
}

function pure(x) {
  return Promise.resolve(x);
}

function bind(x, f) {
  return x.then(Curry.__1(f));
}

var include = Monad$CoreCategory.Make1({
      pure: pure,
      bind: bind
    });

var map = include.map;

var replace = include.replace;

var $$void = include.$$void;

var FunctorInfix = include.FunctorInfix;

var $less$$great = include.$less$$great;

var $less$amp$great = include.$less$amp$great;

var $less$ = include.$less$;

var $$great = include.$$great;

var apply = include.apply;

var liftA2 = include.liftA2;

var applyFirst = include.applyFirst;

var applySecond = include.applySecond;

var ApplyInfix = include.ApplyInfix;

var $less$star$great = include.$less$star$great;

var $star$great = include.$star$great;

var $less$star = include.$less$star;

var $star$star = include.$star$star;

var liftA3 = include.liftA3;

var liftA4 = include.liftA4;

var liftA5 = include.liftA5;

var merge = include.merge;

var pure$1 = include.pure;

var when_ = include.when_;

var unless = include.unless;

var select = include.select;

var SelectiveInfix = include.SelectiveInfix;

var $less$star$question = include.$less$star$question;

var $less$pipe$pipe$great = include.$less$pipe$pipe$great;

var $less$amp$amp$great = include.$less$amp$amp$great;

var orS = include.orS;

var andS = include.andS;

var whenS = include.whenS;

var branch = include.branch;

var ifS = include.ifS;

var fromOptionS = include.fromOptionS;

var anyS = include.anyS;

var allS = include.allS;

var whileS = include.whileS;

var bind$1 = include.bind;

var MonadInfix = include.MonadInfix;

var $great$great$eq = include.$great$great$eq;

var $great$great$tilde = include.$great$great$tilde;

var $great$eq$great = include.$great$eq$great;

var join = include.join;

var forever = include.forever;

var sequenceM = include.sequenceM;

var mapM = include.mapM;

var mapM_ = include.mapM_;

exports.oneOf = oneOf;
exports.fail = fail;
exports.$$catch = $$catch;
exports.map = map;
exports.replace = replace;
exports.$$void = $$void;
exports.FunctorInfix = FunctorInfix;
exports.$less$$great = $less$$great;
exports.$less$amp$great = $less$amp$great;
exports.$less$ = $less$;
exports.$$great = $$great;
exports.apply = apply;
exports.liftA2 = liftA2;
exports.applyFirst = applyFirst;
exports.applySecond = applySecond;
exports.ApplyInfix = ApplyInfix;
exports.$less$star$great = $less$star$great;
exports.$star$great = $star$great;
exports.$less$star = $less$star;
exports.$star$star = $star$star;
exports.liftA3 = liftA3;
exports.liftA4 = liftA4;
exports.liftA5 = liftA5;
exports.merge = merge;
exports.pure = pure$1;
exports.when_ = when_;
exports.unless = unless;
exports.select = select;
exports.SelectiveInfix = SelectiveInfix;
exports.$less$star$question = $less$star$question;
exports.$less$pipe$pipe$great = $less$pipe$pipe$great;
exports.$less$amp$amp$great = $less$amp$amp$great;
exports.orS = orS;
exports.andS = andS;
exports.whenS = whenS;
exports.branch = branch;
exports.ifS = ifS;
exports.fromOptionS = fromOptionS;
exports.anyS = anyS;
exports.allS = allS;
exports.whileS = whileS;
exports.bind = bind$1;
exports.MonadInfix = MonadInfix;
exports.$great$great$eq = $great$great$eq;
exports.$great$great$tilde = $great$great$tilde;
exports.$great$eq$great = $great$eq$great;
exports.join = join;
exports.forever = forever;
exports.sequenceM = sequenceM;
exports.mapM = mapM;
exports.mapM_ = mapM_;
/* include Not a pure module */
