// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Semigroup$CoreCategory = require("./Semigroup.bs.js");

function eq(param, param$1) {
  return true;
}

function compare(param, param$1) {
  return 0;
}

function combine(t, param) {
  return t;
}

var include = Semigroup$CoreCategory.Make0({
      combine: combine
    });

var combine$1 = include.combine;

var Semigroup_infix = include.Semigroup_infix;

var $less$great = include.$less$great;

exports.eq = eq;
exports.compare = compare;
exports.combine = combine$1;
exports.Semigroup_infix = Semigroup_infix;
exports.$less$great = $less$great;
/* include Not a pure module */
